image:
  - Visual Studio 2017

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

install:
  - git submodule update --init
  - cinst strawberryperl
  - set PATH=%PATH%;C:\Strawberry\perl\bin
  - if "%PLATFORM%" equ "x86" set BITS=32
  - if "%PLATFORM%" equ "x64" set BITS=64
  - if "%PLATFORM%" equ "x86" set ARCH=x86
  - if "%PLATFORM%" equ "x64" set ARCH=x86_64
  - if "%PLATFORM%" equ "x86" set PLAT=Win32
  - if "%PLATFORM%" equ "x64" set PLAT=x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars%BITS%.bat"

build_script:
  - cmd: cd Dependencies
  - cmd: openssl-build
  - cmd: cd ..
  - cmd: premake --architecture=%ARCH% vs2017
  - cmd: msbuild Build\P4Win.sln /p:Configuration=%CONFIGURATION% /p:Platform=%PLAT% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /verbosity:minimal
